# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Himekana's
subtitle: 'Fly to the sky.'
description: '明日はきっと晴れるさ。'
keywords:
author: Sakura Yumine
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://asadahimeka.vercel.app
permalink: posts/:abbrlink/
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: hex #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: false #默认为 true， 手改改为 false
    depth:
# permalink: :year/:month/:day/:title/
# permalink_defaults:
#   lang: en
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  auto_detect: false
  line_number: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yun

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# plugins
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -updated
  icon: favicon.png
  autodiscovery: true
  template:

# https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: "“”‘’"
  modifyAnchors: 0
  autolink: true
  mangle: true
  sanitizeUrl: false
  headerIds: true
  lazyload: false
  prependRoot: false
  postAsset: false
  external_link:
    enable: false
    exclude: []
    nofollow: false
  disableNunjucks: false

# https://github.com/hexojs/hexo-server
server:
  compress: true

# https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude:
css_minifier:
  enable: true
  silent: false
  exclude:
    - "*.min.css"
js_minifier:
  enable: true
  mangle: true
  silent: false
  # output:
  # compress:
  exclude:
    - "*.min.js"
    - "**/node_modules/**/*.js"
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false
js_concator:
  enable: false
  bundle_path: "/js/bundle.js"
  front: false
  silent: false

aplayer:
  asset_inject: false
  cdn: https://lib.baomitu.com/aplayer/latest/APlayer.min.js
  style_cdn: https://lib.baomitu.com/aplayer/latest/APlayer.min.css
  meting: true
  meting_cdn: https://npm.elemecdn.com/meting@1/dist/Meting.min.js

live2d:
  enable: false
  # 推荐使用 jsdelivr 的 CDN 来加载
  # scriptFrom: jsdelivr
  scriptFrom: https://code.bdstatic.com/npm/live2d-widget@3.1.4/lib/L2Dwidget.min.js
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # 推荐使用 CDN 来加载模型
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json
    # use: https://cdn.jsdelivr.net/gh/asadahimeka/live2d_demo@master/models/HyperdimensionNeptunia/histoire/index.json
    use: https://pf.wuniutech.com/kari/files/-/live2d_models/histoire/index.json
  display:
    position: right
    width: 165
    height: 382
    hOffset: 0
    vOffset: 100
  mobile:
    show: false
  react:
    opacity: 1
  dialog:
    # 是否开启对话框
    enable: false
    # 是否使用一言
    hitokoto: false

bangumi:
  enable: true
  source: bili
  path: bangumi/index.html
  vmid: 8051085
  title: 'Following Bangumi'
  quote: 'オッサンが番組見てて悪かったな！'
  show: 1
  lazyload: true
  loading:
  metaColor: '#00a1d6'
  color: '#222'
  webp: true
  progress: true

cinema: # 追剧设置
  enable: true
  path: bangumi/cinema.html
  vmid: 8051085
  title: 'Following Cinema'
  quote: '(o-ωｑ)).oO 困'
  show: 1
  lazyload: true
  loading:
  metaColor: '#00a1d6'
  color: '#222'
  webp: true
  progress: true
